### ISSUE TITLE
I get logged on page refresh

### ISSUE THREAD

**Issue by lukasvdberk** [filecoffee/issues#7]
**Describe the bug**
I get logged on page refresh

**To Reproduce**
Login and F5 (also Cntrl+Shift+R)

**Expected behavior**
Not to be logged out

**Screenshots**
op bokken

**Comment by abcdan** [comment]
Has been fixed, currently being deployed.

**Comment by lukasvdberk** [comment]
Awesome thanks!

**Comment by lukasvdberk** [comment]
Maybe next time let the person who created the issue close it? Thanks!
